### ISSUE TITLE
Warning in Google Chromium 52

### ISSUE THREAD

**Issue by chrizzzle** [GoogleChrome/inert-polyfill#2]
Using the inert attribute causes following error while tabbing through the page:
"A DOM event generated from JavaScript has triggered a default action inside the browser. This behavior is non-standard and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5718803933560832 for more details."

It seems to be caused by the following line:

``` javascript
document.dispatchEvent(ev);
```

**Comment by samthor** [comment]
We emulated the user's tab event so that jumping over inert elements would follow the correct tabindex. In some browsers, this still works; most browsers now treat faking user input as an issue though :-)

This might be resolved in future since the tabindex is visible and it's possible to leverage it. It's just slow though.
